server:
  port: 83
  servlet:
    context-path: /consumer
spring:
  application:
    name: nacos-consumer83
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

service-url:
  nacos-user-service: http://nacos-provider
